#!/usr/bin/env node
// Renders README.md into preview.html the way GitHub would show it.
// Local convenience only, preview.html is gitignored.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcName = process.argv[2] || 'README.md';
const outName = srcName.includes('demo') ? 'preview.demo.html' : 'preview.html';
const md = readFileSync(join(ROOT, srcName), 'utf8').replace(/<\/script/gi, '<\\/script');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>awesome-monid preview</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.2/marked.min.js"></script>
<style>
  body { margin: 0; background: #f6f8fa; }
  .frame { max-width: 1012px; margin: 32px auto; background: #fff;
           border: 1px solid #d1d9e0; border-radius: 6px; padding: 48px; }
  .bar { max-width: 1012px; margin: 16px auto -16px; font: 12px ui-monospace, monospace; color: #59636e; }
  @media (prefers-color-scheme: dark) {
    body { background: #010409; }
    .frame { background: #0d1117; border-color: #3d444d; }
    .bar { color: #9198a1; }
  }
</style>
</head>
<body>
<div class="bar">local preview of ${srcName}, generated by scripts/preview.mjs</div>
<article class="markdown-body frame" id="out"></article>
<script id="src" type="text/markdown">${md}</script>
<script>
  document.getElementById('out').innerHTML =
    marked.parse(document.getElementById('src').textContent);
</script>
</body>
</html>
`;

writeFileSync(join(ROOT, outName), html, 'utf8');
console.log(`Wrote ${outName}`);
